name: number_guesser
description: A simple two-player game where one person has to guess the number of the other one.
version: 0.0.1
homepage: https://github.com/marcelgarus/portals

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  portals:
    path: ../../portals
  async: ^2.4.0
